var config = {"startdate":"2016-11-29T00:00:01","stopdate":"2016-11-29T23:59:59","events":[{"name":"WhateverManager.exe - Error","data":[{"date":"2016-11-29T21:26:05Z","detail":"Error when get data : 2335214<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (26)<br>"},{"date":"2016-11-29T21:26:02Z","detail":"Error when get  data : 2335198<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (273)<br>"},{"date":"2016-11-29T21:26:00Z","detail":"Error when get data : 2335202<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (206)<br>"},{"date":"2016-11-29T21:26:00Z","detail":"Error when get data : 2335200<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (247)<br>"},{"date":"2016-11-29T21:25:59Z","detail":"Error when get data : 2335159<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (181)<br>"},{"date":"2016-11-29T21:25:59Z","detail":"Error when get data : 2335193<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (312)<br>"},{"date":"2016-11-29T21:25:58Z","detail":"Error when get  data : 2335019<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (128)<br>"},{"date":"2016-11-29T21:25:58Z","detail":"Error when get  data : 2334872<br><br>-------- Exception ----------------<br>System.Threading.Tasks.TaskCanceledException: A task was canceled.<br>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br><br>---------- Additional info ------------<br>Logger name: A.B.C.Originworker<br>AppDomain: 028be3c8b6da43edbbbad960148f30bf<br>Thread:  (61)<br>"}]}]}